describe('Cypress Homework 2', () => {

    it('Test order functionality', () => {
        cy.visit('https://rahulshettyacademy.com/seleniumPractise/#/')
        cy.get('input.search-keyword').type("brocolli")
        cy.get('button.search-button').click()
        cy.get('h4.product-name' ).should('contain', 'Brocolli')
        cy.get('input.quantity[value="1"]').should('exist')
        cy.get('a.increment').click({ multiple: true }).click()
        cy.get('input.quantity[value="3"]').should('exist')
        cy.contains('ADD TO CART').click()
        cy.get('.added').should("be.visible")
        cy.get('a.cart-icon').click()
        cy.get('.cart-preview  [src *= "broccoli"]').should("be.visible")
        cy.contains('PROCEED TO CHECKOUT').click()
        cy.contains('Brocolli').should('be.visible')
        cy.get('input.promoCode').type("Test")
        cy.contains('Apply').click()
        cy.wait(7000)
        cy.get('.promoInfo')
            .should("be.visible").and('have.text', "Invalid code ..!")
        cy.contains('Place Order').click()
        cy.get('select:first-of-type').select('Armenia')
        cy.get('.chkAgree').check()
        cy.contains('Proceed').click()
        cy.contains('Thank you'). should('be.visible')
    })
})
